### ISSUE TITLE
dpi＝3的时候，1px边框显示不对。

### ISSUE THREAD

**Issue by vxzhong** [doyoe/Yo#24]
应该是sass没有处理'/'为除法 
 -webkit-transform: scale(1/3);
  transform: scale(1/3);

**Comment by doyoe** [comment]
你说的是dpr吧？

能具体描述下显示不对，显示成什么了么？

**Comment by vxzhong** [comment]
是的，dpr，写错了。
![image](https://cloud.githubusercontent.com/assets/86217/15103191/f9cc0cf0-15da-11e6-9a37-d333207ee8dd.png)
上面是在6plus下，日期组件的显示，1px border超过了边框。

我把transform: scale(1/3); 改成transform: scale(0.3333);显示就正常了。
@mixin border里
``` scss
@include responsive(retina3x) {
            width: 300%;
            height: 300%;
            @include transform(scale(1/3));
            @if $radius != null {
                border-radius: $radius * 3;
            }
        }
```
可能是这里@include transform(scale(1/3))没有做除法。
