### ISSUE TITLE
关于使用yo后的css代码规范

### ISSUE THREAD

**Issue by MrKou47** [doyoe/Yo#36]
之前的css代码是按照这种来编写的

``` css
div {
    display: block; // 盒模型
    position: absolute; // 定位
    left: 0; // 定位相关
    width: 100%; // 盒子长宽
    text-align: center; // 文字相关↓
    line-height: 1.5;
    border: 1px solid #ccc; // border padding margin ↓
    padding: 10px; 
    margin: 0 auto;
    background-color: #fff; //颜色相关 ↓
    color: red;
    transition: all .2s; //动画
}
```

但是使用yo之后不知道该怎么排版写好的scss了，例如 

``` scss
div {
    @include flexbox(flex);
    @include justify-content(center);
    @include align-items(center);
    @include flex(1);
    @include yo-checked(
        $name: pay,
        $bgcolor: #fff,
        $on-bgcolor: #24aa42,
        $border-width: 1px,
        $border-color: #ccc,
        $on-border-color: #24aa42,
        $color: #fff,
        $radius: 50%
    );
    position: absolute;
    left: 0;
    width: 100%;
    text-align: center;
    line-height: 1.5;
    border: 1px solid #ccc;
    padding: 10px;
    margin: 0 auto;
    background-color: #fff;
    color: red;
    transition: all .2s;
}
```

这样排版感觉好乱，想请教一下贵司使用yo的时候是按照什么循序编写的
